spring.application.name=notification-service

server.port = 8090

spring.datasource.url=jdbc:mysql://localhost:3306/admin_db
spring.datasource.username=root
spring.datasource.password=RLK8888@NDA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# EMAIL CONFIGURATION

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kaushalsangwan530@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#REDIS CONFIGURATION
spring.cache.type = REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379



# KAFKA CONFIGURATION

# Kafka bootstrap servers (comma-separated list of brokers)
spring.kafka.bootstrap-servers=localhost:9092

# Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Consumer configuration
spring.kafka.consumer.group-id=send-notification
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=true

# Consumer concurrency (number of threads)
spring.kafka.listener.concurrency=3

# Poll timeout
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.max.poll.records=500

# Security (if using SASL/SSL)
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="pass";


# FIREBASE CONFIGURATION

firebase.database.url=https://myapp-12345-default-rtdb.firebaseio.com/
firebase.credentials.path=classpath:firebase-service-account.json